### ISSUE TITLE
Think about changing our logo 

### ISSUE THREAD

**Issue by samuki** [samuki/alpha-bomber#5]

**Comment by Genius-G** [comment]
![grafik](https://user-images.githubusercontent.com/44967870/111886755-81464100-89d0-11eb-8673-0681e91629bb.png)

**Comment by Genius-G** [comment]
![grafik](https://user-images.githubusercontent.com/44967870/111886776-a9ce3b00-89d0-11eb-8af6-ff4a9235e790.png)

**Comment by Genius-G** [comment]
![grafik](https://user-images.githubusercontent.com/44967870/111886785-b9e61a80-89d0-11eb-9363-266bfc891436.png)

**Comment by samuki** [comment]
nice
